// Generated by CoffeeScript 1.6.2
(function() {
  this.AppController = function($scope, angularFire, FIREBASE_URL) {
    var freshMatrix, myTurn, otherColor, ref;

    $scope.game = {};
    freshMatrix = [
      [
        {
          color: 'white'
        }, {
          color: 'white'
        }, {
          color: 'white'
        }, {
          color: 'white'
        }
      ], [
        {
          color: 'white'
        }, {
          color: 'white'
        }, {
          color: 'white'
        }, {
          color: 'white'
        }
      ], [
        {
          color: 'white'
        }, {
          color: 'white'
        }, {
          color: 'white'
        }, {
          color: 'white'
        }
      ], [
        {
          color: 'white'
        }, {
          color: 'white'
        }, {
          color: 'white'
        }, {
          color: 'white'
        }
      ]
    ];
    $scope.game.matrix = angular.copy(freshMatrix);
    ref = new Firebase(FIREBASE_URL);
    angularFire(ref, $scope, "game");
    $scope.game.turn = "red";
    $scope.myColor = "white";
    $scope.makeMove = function(color, row, column) {
      if (myTurn(color) && ($scope.game.matrix[row][column]['color'] === 'white')) {
        $scope.game.matrix[row][column]['color'] = color;
        return $scope.game.turn = otherColor(color);
      } else {
        return alert("Can't do that");
      }
    };
    $scope.clearMatrix = function() {
      return $scope.game.matrix = angular.copy(freshMatrix);
    };
    otherColor = function(color) {
      var newColor;

      if (color === "red") {
        newColor = "blue";
      } else {
        newColor = "red";
      }
      return newColor;
    };
    return myTurn = function(color) {
      var ret;

      if (color === $scope.game.turn) {
        ret = true;
      } else {
        ret = false;
      }
      return ret;
    };
  };

}).call(this);
